exec-once = systemctl --user start hyprpolkitagent
exec-once = sh -lc 'if ! kojarchy-toggle-enabled waybar-off; then waybar; fi'
exec-once = dunst
exec-once = swayosd-server
exec-once = swaybg -i ~/dotfiles/wallpapers/pallete.png -m fill
exec-once = [workspace 1 silent] kitty
exec-once = [workspace 2 silent] flatpak run app.zen_browser.zen
