format = """
(#a6adc8)\
[ 󰘧 ](bg:#a6adc8 fg:#11111b)\
[](bg:#89b4fa fg:#a6adc8)\
$directory\
[](fg:#89b4fa bg:#313244)\
$git_branch\
$git_status\
[](fg:#313244 bg:#181825)\
$nodejs\
$python\
$rust\
$golang\
$php\
[ ](fg:#181825)\
\n$character"""

[directory]
style = "fg:#15161E bg:#89b4fa"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#313244"
format = '[[ $symbol $branch ](fg:#89b4fa bg:#313244)]($style)'

[git_status]
style = "bg:#313244"
format = '[[($all_status$ahead_behind)](fg:#89b4fa bg:#313244)]($style)'
ahead = '⇡${count} '
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
behind = '⇣${count} '
modified = '!${count} '
staged = '+${count} '
stashed = '*${count} '
untracked = '?${count} '
renamed = '»${count} '
deleted = '✘${count} '

[nodejs]
symbol = ""
style = "bg:#181825"
format = '[[ $symbol ($version) ](fg:#89b4fa bg:#181825)]($style)'

[rust]
symbol = ""
style = "bg:#181825"
format = '[[ $symbol ($version) ](fg:#89b4fa bg:#181825)]($style)'

[python]
symbol = " "
style = "bg:#181825"
format = '[[ $symbol ($version) ](fg:#89b4fa bg:#181825)]($style)'

[golang]
symbol = ""
style = "bg:#181825"
format = '[[ $symbol ($version) ](fg:#89b4fa bg:#181825)]($style)'

[php]
symbol = ""
style = "bg:#181825"
format = '[[ $symbol ($version) ](fg:#89b4fa bg:#181825)]($style)'
