#!/usr/bin/env bash

# NVM
rm -rf ~/.npm ~/.config/nvm

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

source ~/.zshrc

nvm install --lts
nvm use --lts

NPM_PACKAGES="depcheck eslint graphql graphql-language-service-cli license lua-fmt neovim pm2 prettier typescript tree-sitter-cli yarn"

npm install -g $NPM_PACKAGES

