#!/usr/bin/env zsh

# vim-plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Binaries
echo "[  ] installing ripgrep and bat"
sudo apt install -o Dpkg::Options::="--force-overwrite" bat ripgrep
if [ $? -eq 0 ]; then
	echo "[OK] installed ripgrep and bat"
else
	echo "[X]  ripgrep and bat failed to install"
fi

echo "------------------------"
echo "[  ] installing fd"
sudo apt install fd-find
if [ $? -eq 0 ]; then
	ln -s $(which fdfind) ~/.local/bin/fd
	if [ $? -eq 0 ]; then
		echo "[OK] installed and linked fd"
	else
		echo "[X]  fd failed to link"
	fi
else
	echo "[X]  fd failed to install "
fi

deps=('fzf' 'lldb' 'curl')

for dep in $deps; do
	echo "------------------------"
	echo "[  ] installing $dep"
	sudo apt install $dep -y
	if [ $? -eq 0 ]; then
		echo "[OK] $dep installed"
	else
		echo "[X]  $dep failed to install"
	fi
done

# NVM
rm -rf ~/.npm ~/.config/nvm

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

nvm install --lts
nvm use --lts

NPM_PACKAGES="depcheck,eslint,graphql,graphql-language-service-cli,license,lua-fmt,neovim,pm2,prettier,typescript,tree-sitter-cli,yarn"

for package in $(echo $NPM_PACKAGES | sed "s/,/ /g"); do
  npm install -g $package
done

