#!/usr/bin/env bash

if ! command -v nala >/dev/null 2>&1; then
  echo "nala is not installed"
  exit 1
fi

echo "[  ] installing ripgrep and bat"
sudo apt install -o Dpkg::Options::="--force-overwrite" bat ripgrep
if [ $? -eq 0 ]; then
	echo "[OK] installed ripgrep and bat"
else
	echo "[X]  ripgrep and bat failed to install"
fi

GENERAL_DEPS="fzf curl fd-find zsh tmux"
UBUNTO_DEPS="i3 feh ranger caca-utils highlight atool w3m poppler-utils mediainfo picom docker-ce docker-ce-cli containerd.io docker-compose-plugin pasystray lxappearance pavucontrol pavumeter polybar playerctl"
ASTUDIO_DEPS="openjdk-11-jdk"

sudo nala install $deps
echo "[OK] Sucessfullt installed $deps"
