#!/usr/bin/env bash

if pgrep -x hyprsunset > /dev/null; then
    pkill -x hyprsunset
    notify-send "'hyprsunset' stopped"
else
    hyprsunset --temperature 4000 &
    notify-send "'hyprsunset' started"
fi
