[bindings]
"g" = "move_top"
"G" = "move_bottom"

[theme]
background = "#1e1e2e"
primary = "#cdd6f4"
secondary = "#94e2d5"
title = "#89b4fa"
playing = "#a6e3a1"
playing_bg = "#1e1e2e"
highlight = "#cdd6f4"
highlight_bg = "#536994"
playing_selected = "#a6e3a1"
error = "#1e1e2e"
error_bg = "#f38ba8"
statusbar = "#89b4fa"
statusbar_bg = "#313244"
statusbar_progress = "#89b4fa"
cmdline = "#89b4fa"
cmdline_bg = "#181825"
