format = """
(#969eaa)\
[ 󰘧 ](bg:#969eaa fg:#0b0e14)\
[](bg:#59c2ff fg:#969eaa)\
$directory\
${custom.git_repo_name}\
[](fg:#59c2ff bg:#1b1f29)\
$git_branch\
$git_status\
[](fg:#1b1f29 bg:#141821)\
$nodejs\
$python\
$rust\
$golang\
$php\
[ ](fg:#141821)\
\n$character"""

[directory]
style = "fg:#0b0e14 bg:#59c2ff"
format = "[ $path ]($style)"
before_repo_root_style = "fg:#0b0e14 bg:#59c2ff"
repo_root_format = ""
repo_root_style = "fg:#0b0e14 bg:#59c2ff"
truncation_length = 3
truncation_symbol = "…/"

[custom.git_repo_name]
command = '''
repo="$(git remote get-url origin 2>/dev/null)"
if [ -z "$repo" ]; then
  repo="$(git rev-parse --show-toplevel)"
fi
repo="${repo%/}"
repo="${repo##*/}"
repo="${repo##*:}"
printf '%s' "${repo%.git}"
'''
require_repo = true
when = true
style = "fg:#0b0e14 bg:#59c2ff"
format = "[ $output ]($style)"

[git_branch]
symbol = ""
style = "bg:#1b1f29"
format = '[[ $symbol $branch ](fg:#59c2ff bg:#1b1f29)]($style)'

[git_status]
style = "bg:#1b1f29"
format = '[[($all_status$ahead_behind)](fg:#59c2ff bg:#1b1f29)]($style)'
ahead = '⇡${count} '
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
behind = '⇣${count} '
modified = '!${count} '
staged = '+${count} '
stashed = '*${count} '
untracked = '?${count} '
renamed = '»${count} '
deleted = '✘${count} '

[nodejs]
symbol = ""
style = "bg:#141821"
format = '[[ $symbol ($version) ](fg:#59c2ff bg:#141821)]($style)'

[rust]
symbol = ""
style = "bg:#141821"
format = '[[ $symbol ($version) ](fg:#59c2ff bg:#141821)]($style)'

[python]
symbol = " "
detect_extensions = []
detect_files = []
style = "bg:#141821"
format = '[[ $symbol ($version) ($virtualenv)](fg:#59c2ff bg:#141821)]($style)'

[golang]
symbol = ""
style = "bg:#141821"
format = '[[ $symbol ($version) ](fg:#59c2ff bg:#141821)]($style)'

[php]
symbol = ""
style = "bg:#141821"
format = '[[ $symbol ($version) ](fg:#59c2ff bg:#141821)]($style)'
