format = """
[  ](fg:#090c0c bg:#6b7280)\
[](fg:#6b7280 bg:#374151)\
$directory\
[](fg:#374151 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#111827)\
\n$character"""

right_format = """
$nodejs\
$python\
$rust\
$golang\
$conda\
"""

[directory]
style = "fg:#e3e5e5 bg:#374151"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind)](fg:#769ff0 bg:#394260)]($style)'
ahead = '⇡${count} '
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
behind = '⇣${count} '
modified = '!${count} '
staged = '+${count} '
stashed = '*${count} '
untracked = '?${count} '
renamed = '»${count} '
deleted = '✘${count} '

[nodejs]
symbol = ""
style = "bg:#1e293b"
format = '[[](bg:#000000 fg:#1e293b)[ $symbol ($version) ](fg:#fca5a5 bg:#1e293b)]($style)'

[python]
symbol = " "
style = "bg:#334155"
format = '[[](bg:#1e293b fg:#334155)[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )](fg:#facc15 bg:#334155)]($style)'

[conda]
style = "bg:#334155 dimmed green"
format = '[\($environment\)]($style) '

[rust]
symbol = ""
style = "bg:#475569"
format = '[[](bg:#334155 fg:#475569)[ $symbol ($version) ](fg:#f1f5f9 bg:#475569)]($style)'

[golang]
symbol = ""
style = "bg:#64748b"
format = '[[](bg:#475569 fg:#64748b)[ $symbol ($version) ](fg:#ffffff bg:#64748b)]($style)'
