#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config focused_border_color "#7199EE"
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true
bspc config border_width 1

for window in $(bspc query -N -n .window); do
  bspc config -w "$window" border_width 3
done

xsetroot -cursor_name left_ptr &
feh --bg-fill "$HOME"/dotfiles/wallpapers/d.jpg
"$HOME"/.config/polybar/launch.sh
"$HOME"/.config/picom/launch.sh
