include current-theme.conf

enable_audio_bell no
background_opacity 1
background_blur 100
hide_window_decorations yes
cursor_trail 3

font_family      FiraCode Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.0

window_padding_width 6

modify_font cell_height 120%

map shift+enter send_text all \x1b[13;2u
map cmd+1 send_text all \x01\x31
map cmd+2 send_text all \x01\x32
map cmd+3 send_text all \x01\x33
map cmd+4 send_text all \x01\x34
map cmd+5 send_text all \x01\x35
map cmd+6 send_text all \x01\x36
map cmd+7 send_text all \x01\x37
map cmd+8 send_text all \x01\x38
map cmd+9 send_text all \x01\x39
