#!/usr/bin/env bash

prompt="-p Manual:"

# terminal to open manual
terminal="kitty"

# list all manuals
manual="$(man -k . | wofi --show dmenu $prompt | awk '{print $1}')"

# open selected manual with terminal
if [[ ! -z "$manual" ]]; then
    eval "$($terminal -T "Mansearch - Manual Viewer" man "$manual")"
fi

exit 0

