#!/usr/bin/env bash

STATE_FILE="$HOME/.rgb_state"

if [[ -f "$STATE_FILE" && "$(cat "$STATE_FILE")" == "white" ]]; then
    openrgb --mode static --color 000000
    echo "black" > "$STATE_FILE"
    notify-send "RGB lights set to black"
else
    openrgb --mode static --color ffffff
    echo "white" > "$STATE_FILE"
    notify-send "RGB lights set to white"
fi

